CREATE DATABASE bnksystem;
CREATE USER bnkuser WITH ENCRYPTED PASSWORD 'bnkuser';
GRANT ALL PRIVILEGES ON DATABASE bnksystem TO bnkuser;

CREATE ROLE crdusr LOGIN PASSWORD 'crdusr';

CREATE SCHEMA IF NOT EXISTS crd_sys AUTHORIZATION crdusr;
